# Generated by Django 3.1.7 on 2021-03-01 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Salas',
        ),
    ]
